name: React Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload build folder
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Deploy React App to /var/www/html
        run: |
          echo "Deploying React app to /var/www/html"
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
