name: React Build and Deploy

on:
  push:
    branches: [envi]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to local directory
        run: |
          sudo rm -rf /var/www/html/my-react-app/*
          sudo cp -r build/* /var/www/html/my-react-app/
